### ISSUE TITLE
Fix dev container kinit failed

### ISSUE THREAD

**Issue by shiywang** [openshift/elliott#97] opened 2019-12-04 05:33 UTC
```
[dev@dbaf7d0152d0 elliott]$ kinit shiywang
kinit: Invalid UID in persistent keyring name while getting default ccache
```

**Comment by vfreex** [comment] 2019-12-09 08:39
@shiywang I can't reproduce with the latest version. Can you check if https://github.com/openshift/elliott/pull/95 fix this?

**Comment by vfreex** [comment] 2020-01-02 04:35
This is fixed by https://github.com/openshift/elliott/pull/95

**Closed by vfreex** 2020-01-02 04:35 UTC
